#!/bin/bash

#SBATCH --job-name=indexBWA      
#SBATCH --mail-type=ALL
#SBATCH --mail-user=marilisa.montemurro@polito.it
#SBATCH --cpus-per-task=4
#SBATCH --partition=global
#SBATCH --time=1:00:00
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --mem=8192M
#SBATCH --output=indexBWA_%j.log

#Build bwa reference files
ASSEMBLY=$1

bwa index ${ASSEMBLY}.fa
echo "BWA index built for assembly:" ${ASSEMBLY}
touch bwaBUILT
