#!/bin/bash

#SBATCH --job-name=mapBWA   
#SBATCH --mail-type=ALL
#SBATCH --mail-user=marilisa.montemurro@polito.it
#SBATCH --cpus-per-task=4
#SBATCH --partition=global
#SBATCH --time=2:00:00
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=2
#SBATCH --mem=8192M
#SBATCH --output=mapBWA_%j.log

ASSEMBLY=$1
IN=$2
LENGTH=$3

bwa aln -t 4 ${ASSEMBLY}.fa ${IN}_${LENGTH}_frags > ${TMPDIR}/${IN}_${LENGTH}_frags.sai

bwa samse -n 1 ${ASSEMBLY}.fa ${TMPDIR}/${IN}_${LENGTH}_frags.sai ${IN}_${LENGTH}_frags | \
  grep "NM:i:0" | \
  awk '$5 >= 30{print $3"\t"$4}' | \
  grep -w $IN | \
  sort -k2,2g > ${IN}_${LENGTH}_bwa_done

rm ${TMPDIR}/${IN}_${LENGTH}_frags.sai

for size in `cat binsizes`; do
  #/opt/uge/bin/lx-amd64/qsub -V -cwd -l m_mem_free=3G -v LENGTH=$LENGTH -v SIZE=$size -v TYPE=bwa -v IN=$IN /seq/schatz/mschatz/ginkgo/genomes/scripts/binBWA
  /home/mmontemurro/ginkgo/genomes/scripts/binBWA $LENGTH $size "bwa" $IN
done

touch bwa_done

